[package]
name = "csv-parser"
version = "0.1.0"
authors = ["Lord Jerry <lovinjerry004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexer = { path = "src/lexer", version = "0.1.0" }
parser = { path = "src/parser", version = "0.1.0" }
