[package]
name = "parser"
version = "0.1.0"
authors = ["Jeremiah Ajayi <lovinjerry004@gmail.com>"]
license = ""
edition = "2018"

[features]
debug = []

[lib]
name = "parser"
path = "parser.rs"

[dependencies]
lexer = { path = "../lexer/", version = "0.1.0" }
